In [5]:
from transformers import TFAutoModel, AutoTokenizer

In [3]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

2024-04-09 12:15:55.150768: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2024-04-09 12:15:55.150837: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2024-04-09 12:15:55.150857: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2024-04-09 12:15:55.150907: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-04-09 12:15:55.150936: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relation

In [8]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [16]:
input = tokenizer(['hello world', 'hello how are you'], padding = True, truncation = True, return_tensors='tf')
input

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 101, 7592, 2088,  102,    0,    0],
       [ 101, 7592, 2129, 2024, 2017,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [18]:
model(input)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-1.68883756e-01,  1.36063516e-01, -1.39400631e-01, ...,
         -6.25112534e-01,  5.21728694e-02,  3.67145777e-01],
        [-3.63274485e-01,  1.41218156e-01,  8.79987717e-01, ...,
          1.04330614e-01,  2.88757414e-01,  3.72679204e-01],
        [-6.98594093e-01, -6.98797822e-01,  6.45025298e-02, ...,
         -2.21036404e-01,  9.86776501e-03, -5.93979418e-01],
        [ 8.30982983e-01,  1.23666808e-01, -1.51189953e-01, ...,
          1.03097424e-01, -6.77926600e-01, -2.62851775e-01],
        [-4.02666271e-01, -1.92825329e-02,  5.73250055e-01, ...,
         -2.06568196e-01,  2.33856291e-02,  2.01263204e-01],
        [-6.22840822e-01, -2.74535656e-01,  1.81175709e-01, ...,
         -1.29448786e-01, -3.83912474e-02, -5.73319346e-02]],

       [[ 3.53770144e-02,  4.97097336e-03, -1.63990170e-01, ...,
         -2.94695139e-01,  1.00460052e-01,  2.69069970e-01]

In [3]:
text = 'I love 🍕! shall we book a 🚖 to gizza?'
text = text.encode("utf-8")
text


b'I love \xf0\x9f\x8d\x95! shall we book a \xf0\x9f\x9a\x96 to gizza?'

In [4]:
decoded_text = text.decode('utf-8')
decoded_text

'I love 🍕! shall we book a 🚖 to gizza?'

In [2]:
from PIL import Image
from pytesseract import image_to_string
filename = "screenshot.png"
text = image_to_string(Image.open(filename))
text

'We notice that there are two errors in the output of the OCR system in this case.\nDepending on the quality of the original scan, OCR output can potentially have\nlarger amounts of errors. How do we clean up this text before feeding it into the next\nstage of the pipeline? One approach is to run the text through a spell checker such as\npyenchant [28], which will identify misspellings and suggest some alternatives. More\nrecent approaches use neural network architectures to train word/character-based\nlanguage models, which are in turn used for correcting OCR text output based on the\ncontext [29].\n'

In [1]:
import nltk

In [3]:
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nischalchand/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:

from nltk.tokenize import sent_tokenize, word_tokenize
my_text = """In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life. If we were asked to
build such an application, think about how we would approach doing so at our organization. We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them. Since language processing is involved, we would also list all the forms of text processing needed at each step. This step-by-step processing of text is known as pipeline. It is the series of steps involved in building any NLP model. These steps are common in every NLP project, so it
makes sense to study them in this chapter. Understanding some common procedures in any NLP pipeline will enable us to get started on any NLP problem encountered in the workplace. Laying out and developing a text-processing pipeline is seen as a starting point for any NLP application development process. In this chapter, we will learn about the various steps involved and how they play important roles in solving the NLP problem and we’ll see a few guidelines
about when and how to use which step. In later chapters, we’ll discuss
specific pipelines for various NLP tasks (e.g., Chapters 4–7)."""

my_sentences = sent_tokenize(my_text)
my_sentences


['In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life.',
 'If we were asked to\nbuild such an application, think about how we would approach doing so at our organization.',
 'We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them.',
 'Since language processing is involved, we would also list all the forms of text processing needed at each step.',
 'This step-by-step processing of text is known as pipeline.',
 'It is the series of steps involved in building any NLP model.',
 'These steps are common in every NLP project, so it\nmakes sense to study them in this chapter.',
 'Understanding some common procedures in any NLP pipeline will enable us to get started on any NLP problem encountered in the workplace.',
 'Laying out and developing a text-processing pipeline is seen as a starting point for any NLP application developm

In [5]:
for sentences in my_sentences:
    print(sentences)
    print(word_tokenize(sentences))

In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life.
['In', 'the', 'previous', 'chapter', ',', 'we', 'saw', 'examples', 'of', 'some', 'common', 'NLP', 'applications', 'that', 'we', 'might', 'encounter', 'in', 'everyday', 'life', '.']
If we were asked to
build such an application, think about how we would approach doing so at our organization.
['If', 'we', 'were', 'asked', 'to', 'build', 'such', 'an', 'application', ',', 'think', 'about', 'how', 'we', 'would', 'approach', 'doing', 'so', 'at', 'our', 'organization', '.']
We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them.
['We', 'would', 'normally', 'walk', 'through', 'the', 'requirements', 'and', 'break', 'the', 'problem', 'down', 'into', 'several', 'sub-problems', ',', 'then', 'try', 'to', 'develop', 'a', 'step-by-step', 'procedure', 'to', 'solve', 'them', '.']
Since

In [6]:
my_words = word_tokenize(my_text)
my_words

['In',
 'the',
 'previous',
 'chapter',
 ',',
 'we',
 'saw',
 'examples',
 'of',
 'some',
 'common',
 'NLP',
 'applications',
 'that',
 'we',
 'might',
 'encounter',
 'in',
 'everyday',
 'life',
 '.',
 'If',
 'we',
 'were',
 'asked',
 'to',
 'build',
 'such',
 'an',
 'application',
 ',',
 'think',
 'about',
 'how',
 'we',
 'would',
 'approach',
 'doing',
 'so',
 'at',
 'our',
 'organization',
 '.',
 'We',
 'would',
 'normally',
 'walk',
 'through',
 'the',
 'requirements',
 'and',
 'break',
 'the',
 'problem',
 'down',
 'into',
 'several',
 'sub-problems',
 ',',
 'then',
 'try',
 'to',
 'develop',
 'a',
 'step-by-step',
 'procedure',
 'to',
 'solve',
 'them',
 '.',
 'Since',
 'language',
 'processing',
 'is',
 'involved',
 ',',
 'we',
 'would',
 'also',
 'list',
 'all',
 'the',
 'forms',
 'of',
 'text',
 'processing',
 'needed',
 'at',
 'each',
 'step',
 '.',
 'This',
 'step-by-step',
 'processing',
 'of',
 'text',
 'is',
 'known',
 'as',
 'pipeline',
 '.',
 'It',
 'is',
 'the',
 'seri

In [7]:
from nltk.corpus import stopwords
removed_words = []
my_stopwords = set(stopwords.words('english'))
filtered_sentence = [w for w in my_words if not w.lower() in my_stopwords]

filtered_sentence
 
        
        
        

['previous',
 'chapter',
 ',',
 'saw',
 'examples',
 'common',
 'NLP',
 'applications',
 'might',
 'encounter',
 'everyday',
 'life',
 '.',
 'asked',
 'build',
 'application',
 ',',
 'think',
 'would',
 'approach',
 'organization',
 '.',
 'would',
 'normally',
 'walk',
 'requirements',
 'break',
 'problem',
 'several',
 'sub-problems',
 ',',
 'try',
 'develop',
 'step-by-step',
 'procedure',
 'solve',
 '.',
 'Since',
 'language',
 'processing',
 'involved',
 ',',
 'would',
 'also',
 'list',
 'forms',
 'text',
 'processing',
 'needed',
 'step',
 '.',
 'step-by-step',
 'processing',
 'text',
 'known',
 'pipeline',
 '.',
 'series',
 'steps',
 'involved',
 'building',
 'NLP',
 'model',
 '.',
 'steps',
 'common',
 'every',
 'NLP',
 'project',
 ',',
 'makes',
 'sense',
 'study',
 'chapter',
 '.',
 'Understanding',
 'common',
 'procedures',
 'NLP',
 'pipeline',
 'enable',
 'us',
 'get',
 'started',
 'NLP',
 'problem',
 'encountered',
 'workplace',
 '.',
 'Laying',
 'developing',
 'text-proces

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nischalchand/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [8]:
from string import punctuation
token_puntuation = word_tokenize(punctuation)
token_puntuation

['!',
 '``',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-./',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [9]:
cleaned_list = []
for sentence in filtered_sentence:
    if sentence not in token_puntuation:
        cleaned_list.append(sentence)
        

In [10]:
cleaned_list

['previous',
 'chapter',
 'saw',
 'examples',
 'common',
 'NLP',
 'applications',
 'might',
 'encounter',
 'everyday',
 'life',
 '.',
 'asked',
 'build',
 'application',
 'think',
 'would',
 'approach',
 'organization',
 '.',
 'would',
 'normally',
 'walk',
 'requirements',
 'break',
 'problem',
 'several',
 'sub-problems',
 'try',
 'develop',
 'step-by-step',
 'procedure',
 'solve',
 '.',
 'Since',
 'language',
 'processing',
 'involved',
 'would',
 'also',
 'list',
 'forms',
 'text',
 'processing',
 'needed',
 'step',
 '.',
 'step-by-step',
 'processing',
 'text',
 'known',
 'pipeline',
 '.',
 'series',
 'steps',
 'involved',
 'building',
 'NLP',
 'model',
 '.',
 'steps',
 'common',
 'every',
 'NLP',
 'project',
 'makes',
 'sense',
 'study',
 'chapter',
 '.',
 'Understanding',
 'common',
 'procedures',
 'NLP',
 'pipeline',
 'enable',
 'us',
 'get',
 'started',
 'NLP',
 'problem',
 'encountered',
 'workplace',
 '.',
 'Laying',
 'developing',
 'text-processing',
 'pipeline',
 'seen',
 

In [11]:
from nltk.stem.porter import PorterStemmer

In [12]:
stemmer = PorterStemmer()

In [13]:
stemmed_list = [stemmer.stem(word) for word in cleaned_list]
stemmed_list

['previou',
 'chapter',
 'saw',
 'exampl',
 'common',
 'nlp',
 'applic',
 'might',
 'encount',
 'everyday',
 'life',
 '.',
 'ask',
 'build',
 'applic',
 'think',
 'would',
 'approach',
 'organ',
 '.',
 'would',
 'normal',
 'walk',
 'requir',
 'break',
 'problem',
 'sever',
 'sub-problem',
 'tri',
 'develop',
 'step-by-step',
 'procedur',
 'solv',
 '.',
 'sinc',
 'languag',
 'process',
 'involv',
 'would',
 'also',
 'list',
 'form',
 'text',
 'process',
 'need',
 'step',
 '.',
 'step-by-step',
 'process',
 'text',
 'known',
 'pipelin',
 '.',
 'seri',
 'step',
 'involv',
 'build',
 'nlp',
 'model',
 '.',
 'step',
 'common',
 'everi',
 'nlp',
 'project',
 'make',
 'sens',
 'studi',
 'chapter',
 '.',
 'understand',
 'common',
 'procedur',
 'nlp',
 'pipelin',
 'enabl',
 'us',
 'get',
 'start',
 'nlp',
 'problem',
 'encount',
 'workplac',
 '.',
 'lay',
 'develop',
 'text-process',
 'pipelin',
 'seen',
 'start',
 'point',
 'nlp',
 'applic',
 'develop',
 'process',
 '.',
 'chapter',
 'learn',


In [14]:
import string

def remove_punctuation(stemmed_list):
    return [elem for elem in stemmed_list if elem not in string.punctuation]


cleaned_list = remove_punctuation(stemmed_list)
print(cleaned_list)

['previou', 'chapter', 'saw', 'exampl', 'common', 'nlp', 'applic', 'might', 'encount', 'everyday', 'life', 'ask', 'build', 'applic', 'think', 'would', 'approach', 'organ', 'would', 'normal', 'walk', 'requir', 'break', 'problem', 'sever', 'sub-problem', 'tri', 'develop', 'step-by-step', 'procedur', 'solv', 'sinc', 'languag', 'process', 'involv', 'would', 'also', 'list', 'form', 'text', 'process', 'need', 'step', 'step-by-step', 'process', 'text', 'known', 'pipelin', 'seri', 'step', 'involv', 'build', 'nlp', 'model', 'step', 'common', 'everi', 'nlp', 'project', 'make', 'sens', 'studi', 'chapter', 'understand', 'common', 'procedur', 'nlp', 'pipelin', 'enabl', 'us', 'get', 'start', 'nlp', 'problem', 'encount', 'workplac', 'lay', 'develop', 'text-process', 'pipelin', 'seen', 'start', 'point', 'nlp', 'applic', 'develop', 'process', 'chapter', 'learn', 'variou', 'step', 'involv', 'play', 'import', 'role', 'solv', 'nlp', 'problem', '’', 'see', 'guidelin', 'use', 'step', 'later', 'chapter', '’'

In [21]:
import spacy
sp = spacy.load('en_core_web_sm')
token = sp(u'talking')
for word in token:
    print( word.text, word.lemma_)

talking talk


In [60]:
pip install spacy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 1.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 989.1 kB/s eta 0:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.6/181.6 kB 1.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.8/128.8 kB 1.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.4/488.4 kB 1.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.1/781.1 kB 1.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 1.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 1.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.1 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [25]:
import spacy
nlp = spacy.load('en_core_web_sm')
doc = nlp(u"""Charles Spencer Chaplin was born on 16 April 1889 toHannah Chaplin (born Hannah Harriet Pedlingham Hill) and Charles Chaplin Sr""")
doc
 # for token in doc:
    
#     print(token.text, token.lemma_, token.pos_, token.shape_, token.is_alpha, token.is_stop)

Charles Spencer Chaplin was born on 16 April 1889 toHannah Chaplin (born Hannah Harriet Pedlingham Hill) and Charles Chaplin Sr

In [1]:
import spacy 
sp = spacy.load('en_core_web_sm')
sentence = 'Charles Spencer Chaplin was born on 16 April 1889 to Hannah Chaplin (born Hannah Harriet Pedlingham Hill) and Charles Chaplin Sr'
doc = sp(sentence)
for token in doc:
    print(token.t, token.pos_, token.lemma_)

Charles PROPN Charles
Spencer PROPN Spencer
Chaplin PROPN Chaplin
was AUX be
born VERB bear
on ADP on
16 NUM 16
April PROPN April
1889 NUM 1889
toHannah PROPN toHannah
Chaplin PROPN Chaplin
( PUNCT (
born VERB bear
Hannah PROPN Hannah
Harriet PROPN Harriet
Pedlingham PROPN Pedlingham
Hill PROPN Hill
) PUNCT )
and CCONJ and
Charles PROPN Charles
Chaplin PROPN Chaplin
Sr PROPN Sr


In [35]:
with open('students.txt') as f:
    text = f.readlines()
text

['Dayton high school, 8th grade students information\n',
 '==================================================\n',
 '\n',
 'Name\tbirth day   \temail\n',
 '-----\t------------\t------\n',
 'Virat   5 June, 1882    virat@kohli.com\n',
 'Maria\t12 April, 2001  maria@sharapova.com\n',
 'Serena  24 June, 1998   serena@williams.com \n',
 'Joe      1 May, 1997    joe@root.com\n',
 '\n',
 '\n',
 '\n']

In [47]:
strings = " ".join(text)
strings

'Dayton high school, 8th grade students information\n ==================================================\n \n Name\tbirth day   \temail\n -----\t------------\t------\n Virat   5 June, 1882    virat@kohli.com\n Maria\t12 April, 2001  maria@sharapova.com\n Serena  24 June, 1998   serena@williams.com \n Joe      1 May, 1997    joe@root.com\n \n \n \n'

In [50]:
doc = sp(strings)
emails = []
for token in doc:
    if token.like_email:
        emails.append(token)
emails

[virat@kohli.com, maria@sharapova.com, serena@williams.com, joe@root.com]

In [2]:
text = 'Dr.Strange loves Nepal. He even has one of his movie in nepal'
doc = sp(text)
for sentence in doc.sents:
    print(sentence)

Dr.Strange loves Nepal.
He even has one of his movie in nepal


In [12]:
text='''
Look for data to help you address the question. Governments are good
sources because data from public research is often freely available. Good
places to start include http://www.data.gov/, and http://www.science.
gov/, and in the United Kingdom, http://data.gov.uk/.
Two of my favorite data sets are the General Social Survey at http://www3.norc.org/gss+website/, 
and the European Social Survey at http://www.europeansocialsurvey.org/.
'''

doc = sp(text)
url = [token.text for token in doc if token.like_url]

url

['http://www.data.gov/',
 'http://www.science',
 'http://data.gov.uk/.',
 'http://www3.norc.org/gss+website/',
 'http://www.europeansocialsurvey.org/.']

In [9]:
transactions = "Tony gave two $ to Peter, Bruce gave 500 € to Steve"

doc = sp(transactions)
for token in doc:
    if token.like_num and doc[token.i + 1].is_currency:
        print(token.text, doc[token.i+1].text)
        
   


two $
500 €


In [14]:
import spacy
sp = spacy.load("en_core_web_sm")
doc = sp(' I own Microsoft my annual income is 100,00$')

In [17]:
for ent in doc.ents:
    print(ent.text, ent.label_)

Microsoft ORG
annual DATE
100,00$ MONEY


In [18]:
from spacy import displacy

In [20]:
displacy.render(doc, style = 'ent')

In [38]:
import spacy
sp = spacy.load('en_core_web_sm')

In [36]:
#spacy customization


ar = sp.get_pipe('attribute_ruler')
ar.add([[{"TEXT":"bro"}], [{"TEXT":"brah"}]], {"LEMMA": "Brother"})
text = "bro, i am really exhausted brah, can't we not go?"

In [37]:
doc = sp(text)
for token in doc:
    print(token.text, '|', token.lemma_)

bro | Brother
, | ,
i | I
am | be
really | really
exhausted | exhausted
brah | Brother
, | ,
ca | can
n't | not
we | we
not | not
go | go
? | ?


In [49]:
doc = sp('Elon and Dr.Strange flew to mars yesterday. He carried biryani masala with him')
for token in doc:
    print(token.text, '|', token.pos_, '|', spacy.explain(token.pos_), '|', token.tag_, '|', spacy.explain(token.tag_))

Elon | PROPN | proper noun | NNP | noun, proper singular
and | CCONJ | coordinating conjunction | CC | conjunction, coordinating
Dr. | PROPN | proper noun | NNP | noun, proper singular
Strange | PROPN | proper noun | NNP | noun, proper singular
flew | VERB | verb | VBD | verb, past tense
to | ADP | adposition | IN | conjunction, subordinating or preposition
mars | NOUN | noun | NNS | noun, plural
yesterday | NOUN | noun | NN | noun, singular or mass
. | PUNCT | punctuation | . | punctuation mark, sentence closer
He | PRON | pronoun | PRP | pronoun, personal
carried | VERB | verb | VBD | verb, past tense
biryani | ADJ | adjective | JJ | adjective (English), other noun-modifier (Chinese)
masala | NOUN | noun | NN | noun, singular or mass
with | ADP | adposition | IN | conjunction, subordinating or preposition
him | PRON | pronoun | PRP | pronoun, personal


In [50]:
my_text = """In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life. If we were asked to
build such an application, think about how we would approach doing so at our organization. We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them. Since language processing is involved, we would also list all the forms of text processing needed at each step. This step-by-step processing of text is known as pipeline. It is the series of steps involved in building any NLP model. These steps are common in every NLP project, so it
makes sense to study them in this chapter. Understanding some common procedures in any NLP pipeline will enable us to get started on any NLP problem encountered in the workplace. Laying out and developing a text-processing pipeline is seen as a starting point for any NLP application development process. In this chapter, we will learn about the various steps involved and how they play important roles in solving the NLP problem and we’ll see a few guidelines
about when and how to use which step. In later chapters, we’ll discuss
specific pipelines for various NLP tasks (e.g., Chapters 4–7)."""

In [54]:

doc = sp(my_text)
filtered_token = []
for token in doc:
    if token.pos_ not in ["SPACE", "X", "PUNCT"]:
        filtered_token.append(token.text)
    

In [56]:
filtered_token 

['In',
 'the',
 'previous',
 'chapter',
 'we',
 'saw',
 'examples',
 'of',
 'some',
 'common',
 'NLP',
 'applications',
 'that',
 'we',
 'might',
 'encounter',
 'in',
 'everyday',
 'life',
 'If',
 'we',
 'were',
 'asked',
 'to',
 'build',
 'such',
 'an',
 'application',
 'think',
 'about',
 'how',
 'we',
 'would',
 'approach',
 'doing',
 'so',
 'at',
 'our',
 'organization',
 'We',
 'would',
 'normally',
 'walk',
 'through',
 'the',
 'requirements',
 'and',
 'break',
 'the',
 'problem',
 'down',
 'into',
 'several',
 'sub',
 '-',
 'problems',
 'then',
 'try',
 'to',
 'develop',
 'a',
 'step',
 'by',
 'step',
 'procedure',
 'to',
 'solve',
 'them',
 'Since',
 'language',
 'processing',
 'is',
 'involved',
 'we',
 'would',
 'also',
 'list',
 'all',
 'the',
 'forms',
 'of',
 'text',
 'processing',
 'needed',
 'at',
 'each',
 'step',
 'This',
 'step',
 'by',
 'step',
 'processing',
 'of',
 'text',
 'is',
 'known',
 'as',
 'pipeline',
 'It',
 'is',
 'the',
 'series',
 'of',
 'steps',
 'invo

In [57]:
with open ('news_story.txt') as f:
    text = f.read()

In [58]:
text

'Inflation rose again in April, continuing a climb that has pushed consumers to the brink and is threatening the economic expansion, the Bureau of Labor Statistics reported Wednesday.\n\nThe consumer price index, a broad-based measure of prices for goods and services, increased 8.3% from a year ago, higher than the Dow Jones estimate for an 8.1% gain. That represented a slight ease from March’s peak but was still close to the highest level since the summer of 1982.\n\nRemoving volatile food and energy prices, so-called core CPI still rose 6.2%, against expectations for a 6% gain, clouding hopes that inflation had peaked in March.\n\nThe month-over-month gains also were higher than expectations — 0.3% on headline CPI versus the 0.2% estimate and a 0.6% increase for core, against the outlook for a 0.4% gain.\n\nThe price gains also meant that workers continued to lose ground. Real wages adjusted for inflation decreased 0.1% on the month despite a nominal increase of 0.3% in average hourl

In [62]:
doc = sp(text)

for token in doc:
    print(token.text, '|', token.pos_)
    

Inflation | NOUN
rose | VERB
again | ADV
in | ADP
April | PROPN
, | PUNCT
continuing | VERB
a | DET
climb | NOUN
that | PRON
has | AUX
pushed | VERB
consumers | NOUN
to | ADP
the | DET
brink | NOUN
and | CCONJ
is | AUX
threatening | VERB
the | DET
economic | ADJ
expansion | NOUN
, | PUNCT
the | DET
Bureau | PROPN
of | ADP
Labor | PROPN
Statistics | PROPN
reported | VERB
Wednesday | PROPN
. | PUNCT


 | SPACE
The | DET
consumer | NOUN
price | NOUN
index | NOUN
, | PUNCT
a | DET
broad | ADV
- | PUNCT
based | VERB
measure | NOUN
of | ADP
prices | NOUN
for | ADP
goods | NOUN
and | CCONJ
services | NOUN
, | PUNCT
increased | VERB
8.3 | NUM
% | NOUN
from | ADP
a | DET
year | NOUN
ago | ADV
, | PUNCT
higher | ADJ
than | ADP
the | DET
Dow | PROPN
Jones | PROPN
estimate | NOUN
for | ADP
an | DET
8.1 | NUM
% | NOUN
gain | NOUN
. | PUNCT
That | PRON
represented | VERB
a | DET
slight | ADJ
ease | NOUN
from | ADP
March | PROPN
’s | PART
peak | NOUN
but | CCONJ
was | AUX
still | ADV
close | ADJ
to |

In [63]:
noun_list = []
num_list = []
for token in doc:
    if token.pos_ == "NOUN":
        noun_list.append(token.text)
    if token.pos_ == "NUM":
        num_list.append(token.text)

In [64]:
noun_list

['Inflation',
 'climb',
 'consumers',
 'brink',
 'expansion',
 'consumer',
 'price',
 'index',
 'measure',
 'prices',
 'goods',
 'services',
 '%',
 'year',
 'estimate',
 '%',
 'gain',
 'ease',
 'peak',
 'level',
 'summer',
 'food',
 'energy',
 'prices',
 'core',
 '%',
 'expectations',
 '%',
 'gain',
 'hopes',
 'inflation',
 'month',
 'month',
 'gains',
 'expectations',
 '%',
 'headline',
 '%',
 'estimate',
 '%',
 'increase',
 'core',
 'outlook',
 '%',
 'gain',
 'price',
 'gains',
 'workers',
 'ground',
 'wages',
 'inflation',
 '%',
 'month',
 'increase',
 '%',
 'earnings',
 'year',
 'earnings',
 '%',
 'earnings',
 '%',
 'Inflation',
 'threat',
 'recovery',
 'pandemic',
 'economy',
 'stage',
 'year',
 'growth',
 'level',
 'prices',
 'pump',
 'grocery',
 'stores',
 'problem',
 'inflation',
 'areas',
 'housing',
 'auto',
 'sales',
 'host',
 'areas',
 'officials',
 'problem',
 'interest',
 'rate',
 'hikes',
 'year',
 'pledges',
 'inflation',
 'bank',
 '%',
 'goal',
 'data',
 'job',
 'Credi

In [65]:
num_list

['8.3',
 '8.1',
 '1982',
 '6.2',
 '6',
 '0.3',
 '0.2',
 '0.6',
 '0.4',
 '0.1',
 '0.3',
 '2.6',
 '5.5',
 '2021',
 '1984',
 'one',
 'two',
 'two',
 '2']

In [68]:
count = doc.count_by(spacy.attrs.POS)
count

{92: 96,
 100: 27,
 86: 15,
 85: 39,
 96: 16,
 97: 32,
 90: 34,
 95: 4,
 87: 13,
 89: 10,
 84: 23,
 103: 7,
 93: 19,
 94: 4,
 98: 8,
 101: 1}

In [69]:
doc.vocab[92].text

'NOUN'

In [ ]:
for k,v in count.items():
    print(