In [5]:
from transformers import TFAutoModel, AutoTokenizer

In [3]:
model = TFAutoModel.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

2024-04-09 12:15:55.150768: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2024-04-09 12:15:55.150837: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2024-04-09 12:15:55.150857: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2024-04-09 12:15:55.150907: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-04-09 12:15:55.150936: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relation

In [8]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

In [16]:
input = tokenizer(['hello world', 'hello how are you'], padding = True, truncation = True, return_tensors='tf')
input

{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 101, 7592, 2088,  102,    0,    0],
       [ 101, 7592, 2129, 2024, 2017,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [18]:
model(input)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 6, 768), dtype=float32, numpy=
array([[[-1.68883756e-01,  1.36063516e-01, -1.39400631e-01, ...,
         -6.25112534e-01,  5.21728694e-02,  3.67145777e-01],
        [-3.63274485e-01,  1.41218156e-01,  8.79987717e-01, ...,
          1.04330614e-01,  2.88757414e-01,  3.72679204e-01],
        [-6.98594093e-01, -6.98797822e-01,  6.45025298e-02, ...,
         -2.21036404e-01,  9.86776501e-03, -5.93979418e-01],
        [ 8.30982983e-01,  1.23666808e-01, -1.51189953e-01, ...,
          1.03097424e-01, -6.77926600e-01, -2.62851775e-01],
        [-4.02666271e-01, -1.92825329e-02,  5.73250055e-01, ...,
         -2.06568196e-01,  2.33856291e-02,  2.01263204e-01],
        [-6.22840822e-01, -2.74535656e-01,  1.81175709e-01, ...,
         -1.29448786e-01, -3.83912474e-02, -5.73319346e-02]],

       [[ 3.53770144e-02,  4.97097336e-03, -1.63990170e-01, ...,
         -2.94695139e-01,  1.00460052e-01,  2.69069970e-01]

In [3]:
text = 'I love 🍕! shall we book a 🚖 to gizza?'
text = text.encode("utf-8")
text


b'I love \xf0\x9f\x8d\x95! shall we book a \xf0\x9f\x9a\x96 to gizza?'

In [4]:
decoded_text = text.decode('utf-8')
decoded_text

'I love 🍕! shall we book a 🚖 to gizza?'

In [1]:
from PIL import Image
from pytesseract import image_to_string
filename = "screenshot.png"
text = image_to_string(Image.open(filename))
text

'We notice that there are two errors in the output of the OCR system in this case.\nDepending on the quality of the original scan, OCR output can potentially have\nlarger amounts of errors. How do we clean up this text before feeding it into the next\nstage of the pipeline? One approach is to run the text through a spell checker such as\npyenchant [28], which will identify misspellings and suggest some alternatives. More\nrecent approaches use neural network architectures to train word/character-based\nlanguage models, which are in turn used for correcting OCR text output based on the\ncontext [29].\n'

In [2]:
import nltk

In [3]:
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nischalchand/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:

from nltk.tokenize import sent_tokenize, word_tokenize
my_text = """In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life. If we were asked to
build such an application, think about how we would approach doing so at our organization. We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them. Since language processing is involved, we would also list all the forms of text processing needed at each step. This step-by-step processing of text is known as pipeline. It is the series of steps involved in building any NLP model. These steps are common in every NLP project, so it
makes sense to study them in this chapter. Understanding some common procedures in any NLP pipeline will enable us to get started on any NLP problem encountered in the workplace. Laying out and developing a text-processing pipeline is seen as a starting point for any NLP application development process. In this chapter, we will learn about the various steps involved and how they play important roles in solving the NLP problem and we’ll see a few guidelines
about when and how to use which step. In later chapters, we’ll discuss
specific pipelines for various NLP tasks (e.g., Chapters 4–7)."""

my_sentences = sent_tokenize(my_text)
my_sentences


['In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life.',
 'If we were asked to\nbuild such an application, think about how we would approach doing so at our organization.',
 'We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them.',
 'Since language processing is involved, we would also list all the forms of text processing needed at each step.',
 'This step-by-step processing of text is known as pipeline.',
 'It is the series of steps involved in building any NLP model.',
 'These steps are common in every NLP project, so it\nmakes sense to study them in this chapter.',
 'Understanding some common procedures in any NLP pipeline will enable us to get started on any NLP problem encountered in the workplace.',
 'Laying out and developing a text-processing pipeline is seen as a starting point for any NLP application developm

In [7]:
for sentences in my_sentences:
    print(sentences)
    print(word_tokenize(sentences))

In the previous chapter, we saw examples of some common NLP applications that we might encounter in everyday life.
['In', 'the', 'previous', 'chapter', ',', 'we', 'saw', 'examples', 'of', 'some', 'common', 'NLP', 'applications', 'that', 'we', 'might', 'encounter', 'in', 'everyday', 'life', '.']
If we were asked to
build such an application, think about how we would approach doing so at our organization.
['If', 'we', 'were', 'asked', 'to', 'build', 'such', 'an', 'application', ',', 'think', 'about', 'how', 'we', 'would', 'approach', 'doing', 'so', 'at', 'our', 'organization', '.']
We would normally walk through the requirements and break the problem down into several sub-problems, then try to develop a step-by-step procedure to solve them.
['We', 'would', 'normally', 'walk', 'through', 'the', 'requirements', 'and', 'break', 'the', 'problem', 'down', 'into', 'several', 'sub-problems', ',', 'then', 'try', 'to', 'develop', 'a', 'step-by-step', 'procedure', 'to', 'solve', 'them', '.']
Since

In [10]:
my_words = word_tokenize(my_text)
my_words

['In',
 'the',
 'previous',
 'chapter',
 ',',
 'we',
 'saw',
 'examples',
 'of',
 'some',
 'common',
 'NLP',
 'applications',
 'that',
 'we',
 'might',
 'encounter',
 'in',
 'everyday',
 'life',
 '.',
 'If',
 'we',
 'were',
 'asked',
 'to',
 'build',
 'such',
 'an',
 'application',
 ',',
 'think',
 'about',
 'how',
 'we',
 'would',
 'approach',
 'doing',
 'so',
 'at',
 'our',
 'organization',
 '.',
 'We',
 'would',
 'normally',
 'walk',
 'through',
 'the',
 'requirements',
 'and',
 'break',
 'the',
 'problem',
 'down',
 'into',
 'several',
 'sub-problems',
 ',',
 'then',
 'try',
 'to',
 'develop',
 'a',
 'step-by-step',
 'procedure',
 'to',
 'solve',
 'them',
 '.',
 'Since',
 'language',
 'processing',
 'is',
 'involved',
 ',',
 'we',
 'would',
 'also',
 'list',
 'all',
 'the',
 'forms',
 'of',
 'text',
 'processing',
 'needed',
 'at',
 'each',
 'step',
 '.',
 'This',
 'step-by-step',
 'processing',
 'of',
 'text',
 'is',
 'known',
 'as',
 'pipeline',
 '.',
 'It',
 'is',
 'the',
 'seri

In [15]:
from nltk.corpus import stopwords
my_stopwords = stopwords.words('english')
my_stopwords

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/nischalchand/nltk_data'
    - '/opt/anaconda3/nltk_data'
    - '/opt/anaconda3/share/nltk_data'
    - '/opt/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
